### ISSUE TITLE
Add Shadow to Rocket Image in Home Screen

### ISSUE THREAD

**Issue by pushpinderpalsingh** [pushpinderpalsingh/SpaceDash#25]
Add shadow to rocket on the home screen like the one present on the second screenshot.
![Screenshot 2020-09-26 at 6 10 55 PM](https://user-images.githubusercontent.com/47032662/94341021-cbeb8f80-0023-11eb-9ea8-3bb1408a6d1a.png) ![iPhone XS](https://user-images.githubusercontent.com/47032662/94341026-d017ad00-0023-11eb-8016-1ab7d4089c8c.png)

**Comment by pankova** [comment]
Hello! 🙂 Could I help you with it as Hacktoberfest participating?

**Comment by pushpinderpalsingh** [comment]
Sure that would be awesome. I am assigning this issue to you. You can join the project communication, on slack. The link can be found in the project Readme

While you are here, Do Star the Project. 😃

**Comment by pushpinderpalsingh** [comment]
@pankova are you still working on this?

**Comment by pankova** [comment]
> @pankova are you still working on this?

Hello! Yeah, I faced with trouble of loading dependencies. Could you help?
```bash
> pod install

bundler: failed to load command: pod (/Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod)
Gem::Exception: can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod:23:in `<top (required)>'
```

**Comment by pushpinderpalsingh** [comment]
Are you inside the repo directory while installing pods?

**Comment by pankova** [comment]
Yes)
```bash
➜  SpaceDash git:(develop) pod install
bundler: failed to load command: pod (/Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod)
Gem::Exception: can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod:23:in `<top (required)>'
```

**Comment by pushpinderpalsingh** [comment]
do you have cocoapods installed?

**Comment by pankova** [comment]
> do you have cocoapods installed?

Yes
```bash
➜  ~ pod --version
1.9.3
```
, but in repo folder
```bash
➜  SpaceDash git:(develop) pod --version
bundler: failed to load command: pod (/Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod)
Gem::Exception: can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod:23:in `<top (required)>'
```
I tried to install it, but it didn't help
```
➜  SpaceDash git:(develop) gem install cocoapods
Successfully installed cocoapods-1.9.3
Parsing documentation for cocoapods-1.9.3
Done installing documentation for cocoapods after 1 seconds
WARNING:  Unable to pull data from 'http://gems.alibaba-inc.com/': Errno::ECONNREFUSED: Failed to open TCP connection to gems.alibaba-inc.com:80 (Connection refused - connect(2) for "gems.alibaba-inc.com" port 80) (http://gems.alibaba-inc.com/specs.4.8.gz)
1 gem installed

➜  SpaceDash git:(develop) pod install
bundler: failed to load command: pod (/Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod)
Gem::Exception: can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile?
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
  /Users/maria.pankova/.rbenv/versions/2.6.3/bin/pod:23:in `<top (required)>'
```

**Comment by pushpinderpalsingh** [comment]
Have you checked on StackOverflow if you can find a solution?

**Comment by pankova** [comment]
> Have you checked on StackOverflow if you can find a solution?

Yes. Now I faced a new error
```bash
➜  SpaceDash git:(develop) bundle exec pod install
Traceback (most recent call last):
	4: from /Users/maria.pankova/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
	3: from /Users/maria.pankova/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
	2: from /Users/maria.pankova/.rvm/gems/ruby-2.7.0/bin/pod:23:in `<main>'
	1: from /Users/maria.pankova/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:402:in `block in replace_bin_path'
/Users/maria.pankova/.rvm/gems/ruby-2.7.0/gems/bundler-2.1.4/lib/bundler/rubygems_integration.rb:374:in `block in replace_bin_path': can't find executable pod for gem cocoapods. cocoapods is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```
I will try to figure out the reason after work, thanks! 🙂
